version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html  # ホストのカレントディレクトリをコンテナにマウント
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # nginx コンテナにも同じディレクトリをマウント
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # nginx の設定ファイルをマウント
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS} 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge